#!/bin/sh
DOTS=/data/Projekte/re1/dotfiles

targets=".config/bspwm .config/sxhkd .config/xfce4"

rm -rf .config .local

for target in $targets
do
    dir=$(dirname "${target}")
    mkdir -p $dir
    cp -R ~/$target $DOTS/$dir
    echo "~/$target → $DOTS/$dir"
done

