#! /bin/sh

systemctl --user start bspwm-session.target
feh --bg-fill ~/.background.png &
~/.config/Thunar/tumblerd &

bspc monitor ^1 -d 1 2 3 4
bspc monitor ^2 -d 5 6
bspc monitor ^3 -d 7 8
bspc monitor ^4 -d 9 0

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config -m ^1 top_padding 28

bspc config border_width 3

bspc config normal_border_color     \#2b2e37
bspc config active_border_color     \#5c6370
bspc config focused_border_color    \#abb2bf

bspc config window_gap  12

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config presel_feedback_color       \#abb2bf

bspc rule -a feh state=floating follow=on
bspc rule -a gimp state=floating follow=on

