#! /bin/sh

feh --bg-fill ~/.background.png &
~/.config/Thunar/tumblerd &

autorandr -c

bspc monitor HDMI-1 -d I II III IV
bspc monitor LVDS-1 -d V VI

bspc wm -O HDMI-1 LVDS-1

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config top_padding 0
bspc config -m primary top_padding 28

bspc config border_width 3

bspc config normal_border_color     \#2f343f
bspc config active_border_color     \#e5c07b
bspc config focused_border_color    \#61afef

bspc config window_gap  12

bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config presel_feedback_color       \#abb2bf

bspc rule -a "" desktop=^5  # fix for spotify (https://github.com/baskerville/bspwm/issues/291)
bspc rule -a TelegramDesktop desktop=^5

bspc rule -a feh state=floating
bspc rule -a Gpick state=floating
bspc rule -a Viewnior state=floating
bspc rule -a vlc state=floating
bspc rule -a Xfce4-panel state=floating
