#! /bin/sh

feh --bg-fill ~/.background.png &
~/.config/Thunar/tumblerd &

autorandr -c

bspc monitor HDMI-1 -d 1 2 3 4
bspc monitor LVDS-1 -d 5 6

bspc wm -O HDMI-1 LVDS-1

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config top_padding 0
bspc config -m primary top_padding 28

bspc config border_width 3

bspc config normal_border_color     \#2b2e37
bspc config active_border_color     \#e5c07b
bspc config focused_border_color    \#61afef

bspc config window_gap  12

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config presel_feedback_color       \#abb2bf

bspc rule -a feh state=floating follow=on
bspc rule -a gimp state=floating follow=on
bspc rule -a viewnior state=floating follow=on
